// Generated by scripts/generate-email-worker.js; contains no secrets.
// @deno-types="npm:@types/nodemailer@7"
import nodemailer from 'npm:nodemailer@9';
import { createClient } from 'npm:@supabase/supabase-js@2';

type EmailGuest = {
  email: string;
  name: string;
  bringing_someone: boolean;
  companion_name: string | null;
  lease_id: string;
};
type EventDetails = {
  title: string;
  start: string;
  end: string;
  location: string;
  description: string;
  url: string;
};
type OrganizerGuest = EmailGuest & {
  companion_email: string | null;
  interested_in_speaking: boolean;
};

const EVENT = {"title":"ELAB Commencement Evening","start":"2026-10-17T19:00:00+02:00","end":"2026-10-18T00:00:00+02:00","location":"Munich — location coming soon","description":"Location coming soon, see you there.","url":"https://elab-devops.github.io/ELAB-FALL26-COMMENCEMENT/"};
function escapeHTML(value: unknown): string {
  const entities: Record<string, string> = {
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  };
  return String(value).replace(/[&<>"']/g, character => entities[character]);
}

function confirmationMessage(guest: EmailGuest, event: EventDetails) {
  const date = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Europe/Berlin', weekday: 'short', day: '2-digit', month: 'short', year: 'numeric'
  }).format(new Date(event.start)).toUpperCase();
  const time = new Intl.DateTimeFormat('en-US', {
    timeZone: 'Europe/Berlin', hour: 'numeric', hour12: true
  }).format(new Date(event.start)).replace(/\s/g, '');
  const eventHeader = `${date}, ${time}, MUC`;
  const opening = "you're in. See you at commencement.";
  const speaking = 'Want to shape the evening? We have room for 2–3 stories. Reply to this email with a few words about what you’d like to share.';
  return {
    from: { name: 'ELAB', address: 'anna.papanakli@tum-ai.com' },
    replyTo: 'anna.papanakli@tum-ai.com',
    to: { address: guest.email },
    subject: 'You’re on the list — ELAB Fall 2026',
    text: `ELAB FALL 2026 | ${eventHeader}\n\nHi ${guest.name},\n\n${opening}\n\nYour calendar invitation will follow.\n\n${speaking}\n\nSee you there,\nELAB`,
    html: `<div style="font-family:Arial,sans-serif;color:#222;max-width:520px;margin:auto;padding:32px 16px;line-height:1.6"><table role="presentation" style="width:100%;border-collapse:collapse;margin-bottom:24px"><tr><td style="padding:0 12px 0 0;font-size:10px;letter-spacing:2px;vertical-align:top">ELAB FALL 2026</td><td style="padding:0;font-size:10px;letter-spacing:.5px;text-align:right;vertical-align:top">${escapeHTML(eventHeader)}</td></tr></table><h1 style="font-weight:400">You’re on the list.</h1><p>Hi ${escapeHTML(guest.name)},</p><p>${escapeHTML(opening)}</p><p>Your calendar invitation will follow.</p><p>${escapeHTML(speaking)}</p><p>See you there,<br>ELAB</p></div>`
  };
}

function organizerMessage(guest: OrganizerGuest) {
  const companions = guest.bringing_someone
    ? `${guest.companion_name || 'Not provided'}\nCompanion email(s): ${guest.companion_email || 'Not provided (optional)'}`
    : 'None';
  const speaking = guest.interested_in_speaking ? 'Yes — interested in sharing a story' : 'Not selected';
  return {
    from: { name: 'ELAB RSVP', address: 'anna.papanakli@tum-ai.com' },
    to: { address: 'anna.papanakli@tum-ai.com' },
    replyTo: { address: guest.email },
    subject: `New ELAB RSVP — ${guest.name.replace(/[\r\n]/g, ' ')}`,
    text: `A new guest has RSVPed.\n\nName: ${guest.name}\nEmail: ${guest.email}\n\nCompanion(s): ${companions}\n\nSpeaking interest: ${speaking}\n\nAdd their email address and any provided companion addresses to your ELAB Google Calendar event, then save and send the invitations.`,
    html: `<div style="font-family:Arial,sans-serif;color:#222;max-width:520px;margin:auto;padding:32px 16px;line-height:1.6"><p style="letter-spacing:3px;font-size:13px">ELAB RSVP</p><h1 style="font-weight:400">A new guest is coming.</h1><p>${escapeHTML(guest.name)}<br>${escapeHTML(guest.email)}</p><p>Companion(s):<br>${escapeHTML(companions).replace(/\n/g, '<br>')}</p><p>Speaking interest: ${escapeHTML(speaking)}</p><p>Add their email address and any provided companion addresses to your ELAB Google Calendar event, then save and send the invitations.</p></div>`
  };
}



Deno.serve(async (request: Request) => {
  const token = Deno.env.get('EMAIL_WORKER_TOKEN');
  if (!token || request.headers.get('Authorization') !== `Bearer ${token}`) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }
  if (request.method !== 'POST') return new Response(null, { status: 405 });
  const username = Deno.env.get('SMTP_USERNAME');
  const password = Deno.env.get('SMTP_PASSWORD');
  if (username !== 'anna.papanakli@tum-ai.com' || !password) {
    return Response.json({ error: 'Email secrets are not configured' }, { status: 503 });
  }
  const adminKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ||
    JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS') || '{}').default;
  if (!adminKey) return Response.json({ error: 'Database credentials missing' }, { status: 503 });
  const db = createClient(Deno.env.get('SUPABASE_URL')!, adminKey);
  const { data: guests, error } = await db.rpc('claim_confirmation_emails');
  if (error) return Response.json({ error: 'Could not claim queued emails' }, { status: 500 });
  const smtp = nodemailer.createTransport({
    host: 'smtp.gmail.com', port: 465, secure: true,
    auth: { user: username, pass: password.replace(/\s/g, '') },
    connectionTimeout: 10000, greetingTimeout: 10000, socketTimeout: 15000
  });
  let sent = 0, failed = 0;
  for (const guest of guests || []) {
    let delivered = false;
    try {
      const result = await smtp.sendMail(confirmationMessage(guest, EVENT));
      delivered = (result.accepted?.length ?? 0) > 0;
    } catch (failure) {
      // Log only error codes, never addresses, passwords, or SMTP response bodies.
      const code = typeof failure === 'object' && failure !== null && 'code' in failure
        && typeof failure.code === 'string' ? failure.code : 'unknown';
      console.error('SMTP failure', code);
    }
    const { error: finishError } = await db.rpc('finish_confirmation_email', {
      recipient_email: guest.email, delivery_lease: guest.lease_id, delivered
    });
    if (finishError) console.error('Could not record delivery status');
    if (delivered) sent++; else failed++;
  }
  const { data: notifications, error: notificationError } = await db.rpc('claim_organizer_notifications');
  let organizerSent = 0, organizerFailed = 0;
  if (notificationError) console.error('Could not claim organizer notifications; check migration');
  for (const guest of notifications || []) {
    let delivered = false;
    try {
      const result = await smtp.sendMail(organizerMessage(guest));
      delivered = (result.accepted?.length ?? 0) > 0;
    } catch (failure) {
      const code = typeof failure === 'object' && failure !== null && 'code' in failure
        && typeof failure.code === 'string' ? failure.code : 'unknown';
      console.error('Organizer SMTP failure', code);
    }
    const { error: finishError } = await db.rpc('finish_organizer_notification', {
      recipient_email: guest.email, delivery_lease: guest.lease_id, delivered
    });
    if (finishError) console.error('Could not record organizer notification status');
    if (delivered) organizerSent++; else organizerFailed++;
  }
  smtp.close();
  return Response.json({ sent, failed, organizerSent, organizerFailed,
    organizerQueueReady: !notificationError });
});
